# Generated by Django 3.2.3 on 2021-06-16 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210616_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='price_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
